### ISSUE TITLE
[WARN] : The pair of images is empty, it is need in debug.

### ISSUE THREAD

**Issue by shanpenghui** [cashiwamochi/SimpleBundleAdjustment#2]
Hello, may I ask, the program input only has 2 pictures, why can I get 2 poses, and what does the warning mean?
![Screenshot from 2021-01-18 18-13-00](https://user-images.githubusercontent.com/35164786/104901852-dfe34480-59b8-11eb-8b60-aec035be9f83.png)

One question is, why in FULL optimization, the dimensionality of the Jacobian matrix has to be 5 degrees of freedom?
Another question is, why can't g2o be optimized for only 3D points, but the program can do it here?
Tks very much. Hope helping.

**Comment by cashiwamochi** [comment]
Thanks for question.

- the program input only has 2 pictures, why can I get 2 poses
I don't understand your point. When we have 2 images, it means that there are 2 cameras, so we get 2 poses as result. However actually only 1 camera is optimized of course.

- what does the warning mean?
Sorry for ambiguous message. Please enable line 174 in ba_example.cc . This message says that, if you use verbose mode of this BA framework, you need to supply 2 images to it in order to draw debugging images.

- One question is, why in FULL optimization, the dimensionality of the Jacobian matrix has to be 5 degrees of freedom?
If we allow all of six DoF to adjust, reprojection error could not converge because of too many DoF. In order to deal with problem, there 2 methods in my knowledge. First, we can make the distance btw Cam1 and Cam2 constant(e.g. 1.0), and second ,we fix one of 6 parameters.

- Another question is, why can't g2o be optimized for only 3D points, but the program can do it here?
I don't know g2o well, but structure-only BA(optimizing only 3d points) is well-known method, thus I think that g2o can do the same thing. Maybe easy template for this case isn't implemented, but if you write jacobian by yourself and use g2o correctly, it should work in my thought.

I hope this simple app helps you.

**Comment by shanpenghui** [comment]
Thank you very much for answering my many questions in such a timely manner.
1. Regarding 2 pictures to get 2 poses, I mean, by comparing 2 pictures we can only get one pose, because we need to use 2 pictures to compare to get one set of data, not two sets data.
2. In the process of using it, I added 2 pictures, but still prompted a warning, so I don’t know what went wrong.
3. Regarding FULL optimization, I am very sorry that I do not understand what you mean too much. If it is convenient for you to provide some reference materials, thank you very much.
4. As you said, I seem to have found some information, and I will continue to research.
Finally, thank you very much for your reply and help. I have just started to study SLAM and I am very much looking forward to keeping in touch with you. Thank you again.

**Comment by cashiwamochi** [comment]
1. You're not incorrect. A cam2 pose relative to cam1 is optimized. But as I wrote, every image have each pose.
2. Perhaps it's a bug. Later I'll check.
3. I'm afraid to say that I don't know good English reference because I studied it using Japanese text. However it cited this English document https://hal.inria.fr/inria-00548290/document. Section 9 Gauge Freedom may be useful for you.
4. Good Luck !
